INF2004-Project: src/pathfinding/a_star.h File Reference
a_star.h File Reference
Header file for the a* algorithm.
#include <stdint.h>
#include "binary_heap.h"
#include "maze.h"
Data Structures
struct a_star_path
Macros
#define DEBUG_PRINT(...) printf(__VA_ARGS__)
Typedefs
typedef struct a_star_path a_star_path_t
Functions
void a_star (maze_grid_t *p_grid, maze_grid_cell_t *p_start_node, maze_grid_cell_t *p_end_node)
Runs the A* algorithm on a grid maze to find the shortest path between two points, if one exists. The path can be retrieved by checking the p_came_from field of each node.
a_star_path_t * a_star_get_path (maze_grid_cell_t *p_end_node)
Get the path from the start node to the end node (inclusive).
char * a_star_get_path_str (maze_grid_t *p_grid, a_star_path_t *p_path)
Gets the string representation of the path from the start node to the end node.
int16_t a_star_maze_path_nav_to_buffer (maze_grid_t *p_grid, a_star_path_t *p_path, maze_navigator_state_t *p_navigator, uint8_t *p_buffer, uint16_t buffer_size)
Inserts the maze, path and navigator state into a buffer.
int16_t a_star_path_to_buffer (a_star_path_t *p_path, uint8_t *p_buffer, uint16_t buffer_size)
Inserts the path in coordinates from the start node to the end node into a buffer.
Detailed Description
Header file for the a* algorithm.
Author
Christopher Kok (chris.nosp@m.@for.nosp@m.celig.nosp@m.htni.nosp@m.ng.xy.nosp@m.z)
Version
0.1
Date
2023-11-07
Copyright
Copyright (c) 2023
Function Documentation
a_star()
void a_star (maze_grid_t * p_grid, maze_grid_cell_t * p_start_node, maze_grid_cell_t * p_end_node)
Runs the A* algorithm on a grid maze to find the shortest path between two points, if one exists. The path can be retrieved by checking the p_came_from field of each node.
Parameters
[in] p_grid The grid maze.
[in] p_start_node Pointer to the start node.
[in] p_end_node Pointer to the end node.
References binary_heap_insert(), binary_heap::capacity, maze_grid::columns, maze_grid_cell::coordinates, maze_grid_cell::f, maze_grid_cell::g, maze_grid_cell::h, maze_manhattan_dist(), binary_heap::p_array, maze_grid::p_grid_array, maze_grid::rows, and binary_heap::size.
a_star_get_path()
a_star_path_t * a_star_get_path (maze_grid_cell_t * p_end_node)
Get the path from the start node to the end node (inclusive).
Parameters
p_end_node Pointer to the end node.
Returns
path_t* Pointer to the path.
References maze_grid_cell::g, a_star_path::length, maze_grid_cell::p_came_from, and a_star_path::p_path.
a_star_get_path_str()
char * a_star_get_path_str (maze_grid_t * p_grid, a_star_path_t * p_path)
Gets the string representation of the path from the start node to the end node.
Parameters
p_grid Pointer to the grid maze.
p_path Pointer to the path.
Returns
char* The string representation of the path.
References maze_grid::columns, maze_grid_cell::coordinates, a_star_path::length, maze_get_dir_from_to(), maze_get_string(), MAZE_NONE, maze_grid_cell::p_came_from, and a_star_path::p_path.
a_star_maze_path_nav_to_buffer()
int16_t a_star_maze_path_nav_to_buffer (maze_grid_t * p_grid, a_star_path_t * p_path, maze_navigator_state_t * p_navigator, uint8_t * p_buffer, uint16_t buffer_size)
Inserts the maze, path and navigator state into a buffer.
Parameters
p_grid Pointer to the maze grid.
p_path Pointer to the path generated by A*, NULL if no path exists.
p_navigator Pointer to the navigator state.
p_buffer Pointer to the buffer to store the maze, path and navigator state in.
buffer_size Size of the buffer. Checks if the buffer is large enough.
Returns
int16_t -1 if the buffer is too small, the size of the buffer required otherwise.
References a_star_path_to_buffer(), maze_grid::columns, a_star_path::length, maze_nav_to_buffer(), maze_serialise(), maze_serialised_to_buffer(), maze_uint16_to_uint8_buffer(), and maze_grid::rows.
a_star_path_to_buffer()
int16_t a_star_path_to_buffer (a_star_path_t * p_path, uint8_t * p_buffer, uint16_t buffer_size)
Inserts the path in coordinates from the start node to the end node into a buffer.
Parameters
p_path Pointer to the path generated by the A* algorithm.
p_buffer Pointer to the buffer to store the path in.
buffer_size Size of the buffer. Checks if the buffer is large enough.
Returns
int16_t -1 if the buffer is too small, 0 otherwise.
References maze_grid_cell::coordinates, a_star_path::length, maze_uint16_to_uint8_buffer(), a_star_path::p_path, maze_point::x, and maze_point::y.