INF2004-Project: src/drivers/pid/pid.c File Reference
pid.c File Reference
#include "motor_control.h"
#include "maze.h"
#include "pid.h"
#include "magnetometer.h"
Functions
void bearing_correction (float target_bearing, float current_bearing, pid_params_t *p_pid_params)
Updates the motor differential ratio based on the target bearing and current bearing.
float calculate_pid (float current_bearing, float target_bearing, float current_ratio, pid_params_t *p_pid_params)
Calculates the PID control signal.
void init_pid_error_correction (pid_params_t *p_pid_params)
Sets defaults for PID parameters.
void init_pid_structs (pid_turn_params_t *p_turn_params)
Sets up pid struct(s).
void navigate_car_turn (pid_turn_params_t *p_turn_params, maze_cardinal_direction_t direction)
Function to turn the car and move in a given direction.
Detailed Description
Author
Bryan Seah
Version
0.1
Date
2023-10-29
Copyright
Copyright (c) 2023
Function Documentation
bearing_correction()
void bearing_correction (float target_bearing, float current_bearing, pid_params_t * p_pid_params)
Updates the motor differential ratio based on the target bearing and current bearing.
Parameters
[in] target_bearing Target bearing of the car in degrees.
[out] current_bearing Current bearing of the car in degrees.
[in,out] p_pid_params Pointer to the PID parameters.
References calculate_pid(), pid_params::current_bearing, pid_params::current_ratio, pid_params::epsilon, magneto_get_curr_bearing(), motor_update_ratio(), and pid_params::ratio_to_bearing.
calculate_pid()
float calculate_pid (float current_bearing, float target_bearing, float current_ratio, pid_params_t * p_pid_params)
Calculates the PID control signal.
Parameters
[in] current_bearing Current bearing of the car in degrees.
[in] target_bearing Target bearing of the car in degrees.
[in] current_ratio Current motor differential ratio.
[in,out] p_pid_params Pointer to the PID parameters.
Returns
float Control signal.
References pid_params::integral, pid_params::k_d, pid_params::k_i, pid_params::k_p, PID_DEGREES_NORMALISE, and pid_params::prev_error.
init_pid_error_correction()
void init_pid_error_correction (pid_params_t * p_pid_params)
Sets defaults for PID parameters.
Parameters
[out] p_pid_params Pointer to the PID parameters.
References pid_params::current_bearing, pid_params::current_ratio, pid_params::epsilon, pid_params::integral, pid_params::k_d, pid_params::k_i, pid_params::k_p, pid_params::prev_error, pid_params::ratio_to_bearing, and pid_params::setpoint.
navigate_car_turn()
void navigate_car_turn (pid_turn_params_t * p_turn_params, maze_cardinal_direction_t direction)
Function to turn the car and move in a given direction.
Parameters
[in,out] p_turn_params Pointer to the turn parameters.
[in] direction Direction to turn.
References pid_turn_params::b_is_centered, pid_turn_params::b_is_moved_cell, pid_turn_params::b_is_turn_complete, pid_turn_params::b_is_turning, pid_turn_params::encoder_step_count, init_pid_structs(), MAZE_EAST, MAZE_SOUTH, MAZE_WEST, motor_move_forward(), motor_turn_left(), and motor_turn_right().