pico.main(): {
  style: {
    fill: orchid
  }
  shape: oval
}

"Ultrasound Echo" -> HC-SR04.Echo
HC-SR04.Echo -> Pico.IN.GP03: Digital active high
Pico.IN.GP03 -> Pico.Routines."Ultrasonic Routines"
Pico.Routines."Ultrasonic Routines" -> Pico.OUT.GP02: 16Hz, 10μs pulse
Pico.OUT.GP02 -> HC-SR04.Trig
HC-SR04.Trig -> "Ultrasound Pulse": 8 x 40kHz pulse
# "Ultrasound Pulse" -> "Ultrasound Echo"
Pico.Routines."Ultrasonic Routines": {
  shape: oval
}
Pico.Routines."Ultrasonic Routines" -> pico.main() {
  style.stroke: red
}

"Magnetic Field" -> Magnetometer.M
Acceleration -> Magnetometer.A
Magnetometer.M -> Magnetometer.SDA
Magnetometer.SDA -> Pico.IN.GP00: I2C1 SDA
Magnetometer.SCL -> Pico.IN.GP01: I2C1 SCL
Magnetometer.A -> Magnetometer.SDA
Pico.IN.GP00 -> Pico.Routines."Magnetometer Routines"
Pico.IN.GP01 -> Pico.Routines."Magnetometer Routines"
Pico.Routines."Magnetometer Routines" -> pico.main(): update orientation + acceleration {
  style.stroke: red
}
Pico.Routines."Magnetometer Routines": {
  shape: oval
}

Pico.Routines.PID Routines : {
  shape: oval
}

Pico.Routines.Wifi Routines {
  shape: oval
}

Pico.Routines.Magnetometer Routines -> Pico.Routines.PID Routines: update orientation
Pico.Routines.IR Sensor Routines -> Pico.Routines.PID Routines: update wall detection
Pico.Routines.IR Sensor Routines -> Pico.Routines.Navigation Routines: update wall directions
Pico.Routines.Ultrasonic Routines -> Pico.Routines.Navigation Routines: update obstacle direction
Pico.Routines.Navigation Routines -> Pico.Routines.PID Routines: provide direction to move in
Pico.Routines.PID Routines -> Pico.Routines.Motor Routines: update motor speed
Pico.Routines.Wheel Encoder Routines -> Pico.Routines.PID Routines: update motor differential speed

pico.main() -> Pico.Routines.Wifi Routines: send navigation and navigator state {
  style.stroke: blue
}

pico.main() -> Pico.Routines."Navigation Routines": update state {
  style.stroke: blue
}

Pico.Routines."Navigation Routines" -> pico.main(): update navigator state {
  style.stroke: red
}

Pico.Routines."Navigation Routines": {
  shape: oval
}

"Left Wheel movement" -> "Left Wheel Encoder"
"Left Wheel Encoder".OUT -> Pico.IN.GP22: Digital active low
Pico.IN.GP22 -> Pico.Routines."Wheel Encoder Routines"
Pico.Routines."Wheel Encoder Routines": {
  shape: oval
}
Pico.Routines."Wheel Encoder Routines" -> pico.main(): update speed {
  style.stroke: red
}

"Right Wheel movement" -> Right Wheel Encoder
Right Wheel Encoder.OUT -> Pico.IN.GP21: Digital active low
Pico.IN.GP21 -> Pico.Routines.Wheel Encoder Routines

"IR Light" -> "Left IR Sensor"
"Left IR Sensor".AO -> Pico.IN.GP27: ADC analog reading
Left IR Sensor.DO -> Pico.IN.GP20: Digital active low
Pico.IN.GP27 -> Pico.Routines."IR Sensor Routines"
Pico.IN.GP20 -> Pico.Routines.IR Sensor Routines
Pico.Routines."IR Sensor Routines": {
  shape: oval
}
"IR Light" -> "Front IR Sensor"
"Front IR Sensor".AO -> Pico.IN.GP26: ADC analog reading
Front IR Sensor.DO -> Pico.IN.GP19: Digital active low
Pico.IN.GP26 -> Pico.Routines.IR Sensor Routines
Pico.IN.GP19 -> Pico.Routines.IR Sensor Routines

Pico.Routines."IR Sensor Routines" -> pico.main(): Interrupt on line crossover &&\nbarcode not detected {
  style.stroke: red
}
Pico.Routines."IR Sensor Routines" -> pico.main(): Decoded barcode output {
  style.stroke: red
}

pico.main() -> Pico.Routines."Motor Routines": Directional input + speed {
  style.stroke: blue
}
Pico.Routines."Motor Routines": {
  shape: oval
}

Pico.Routines.Motor Routines -> Pico.OUT.GP10: Left Motor PWM speed
Pico.Routines.Motor Routines -> Pico.OUT.GP11: Right Motor PWM speed
Pico.Routines.Motor Routines -> Pico.OUT.GP14: Right Motor Anti-Clockwise
Pico.Routines.Motor Routines -> Pico.OUT.GP15: Right Motor Clockwise
Pico.Routines.Motor Routines -> Pico.OUT.GP16: Left Motor Clockwise
Pico.Routines.Motor Routines -> Pico.OUT.GP17: Left Motor Anti-Clockwise

Pico.OUT.GP15 -> L298N.IN1
Pico.OUT.GP14 -> L298N.IN2
Pico.OUT.GP16 -> L298N.IN3
Pico.OUT.GP17 -> L298N.IN4

Pico.OUT.GP10 -> L298N.EN B
Pico.OUT.GP11 -> L298N.EN A

L298N.IN1 -> "Right motor"
L298N.IN2 -> "Right motor"
L298N.IN3 -> "Left motor"
L298N.IN4 -> "Left motor"
L298N.EN A -> "Left motor"
L298N.EN B -> "Right motor"
