main(): {
  style: {
    fill: orchid
  }
  shape: oval
}

"Ultrasound Echo" -> HC-SR04.Echo
HC-SR04.Echo -> Pico.GP01: Digital active high
Pico.GP01 -> Routines."Ultrasonic Routines"
Routines."Ultrasonic Routines" -> Pico.GP02: 16Hz, 10μs pulse
Pico.GP02 -> HC-SR04.Trig
HC-SR04.Trig -> "Ultrasound Pulse": 8 x 40kHz pulse
"Ultrasound Pulse" -> "Ultrasound Echo"
Routines."Ultrasonic Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}
Routines."Ultrasonic Routines" -> main()

"Magnetic Field" -> Magnetometer.M
Acceleration -> Magnetometer.A
Magnetometer.M -> Magnetometer.SDA
Magnetometer.SDA -> Pico.GP04: I2C1 SDA
Magnetometer.SCL -> Pico.GP05: I2C1 SCL
Magnetometer.A -> Magnetometer.SDA
Pico.GP04 -> Routines."Magnetometer Routines"
Pico.GP05 -> Routines."Magnetometer Routines"
Routines."Magnetometer Routines" -> main(): update orientation + acceleration
Routines."Magnetometer Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}

main() -> Routines."Navigation Routines": update state
Routines."Navigation Routines" -> main(): provide nav instruction
Routines."Navigation Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}

"Wheel movement" -> "Wheel Encoder"
"Wheel Encoder".OUT -> Pico.GP06: Digital active low
Pico.GP06 -> Routines."Wheel Encoder Routines"
Routines."Wheel Encoder Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}
Routines."Wheel Encoder Routines" -> main(): update speed

"IR Light" -> "IR Sensor"
"IR Sensor".DO -> Pico.GP07: Digital active low
Pico.GP07 -> Routines."IR Sensor Routines"
Routines."IR Sensor Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}
Routines."IR Sensor Routines" -> main(): Interrupt on line crossover &&\nbarcode not detected
Routines."IR Sensor Routines" -> main(): Decoded barcode output

main() -> Routines."Motor Routines": Directional input + speed
Routines."Motor Routines" -> Pico."GP17-GP20": Directional input\ndigital active high
Routines."Motor Routines" -> Pico."GP21-GP22": PWM Speed
Routines."Motor Routines": {
  style: {
    fill: chartreuse
  }
  shape: oval
}

Pico."GP17-GP20" -> L298N."IN1-IN4"
Pico."GP21-GP22" -> L298N."EN A, EN B"
L298N -> "Left motor"
L298N -> "Right motor"
