name: Docs
run-name: docs-${{ github.run_number }}
on:
  push:
    branches: [ "main" ]
permissions:
  contents: write
jobs:
  build_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Install doxygen, graphviz
        if: ${{ env.ACT }}
        run: sudo apt update && sudo apt install -y doxygen graphviz
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - name: Change directory
        run: cd ${{ github.workspace }}
      - name: Clean docs
        run: rm -rf docs
      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1.9.5
        with:
          doxyfile-path: Doxyfile
      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/
